# -*- coding: utf-8 -*-
"""Twitter_Bitcoin_Download_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j_g86QPCMX8cWE4Yl2ZDiV_0fc6TBj6x

## **TWITTER BITCOIN DOWNLOAD MODEL**

pip install twarc

from twarc import Twarc2, expansions
import datetime
import json
import pandas as pd
import csv

# Replace your bearer token below
client = Twarc2(bearer_token="DELETED FOR SECURITY REASONS")

# Writing response from full-archive search to a text file
def main():

    # Specify the start time in UTC for the time period you want Tweets from
    start_time = datetime.datetime(2020, 11, 1, 0, 0, 0, 0, datetime.timezone.utc)

    # Specify the end time in UTC for the time period you want Tweets from
    end_time = datetime.datetime(2020, 11, 30, 0, 0, 0, 0, datetime.timezone.utc)

    # Specify search query
    # Parameters: hashtag Bitcoin or bitcoin, English language,
    # not a retweet, tweet originates from USA
    query = "#Bitcoin OR #bitcoin lang:en -is:retweet place_country:US"
    
    # Name and path of the file where you want the Tweets written to
    file_name = 'BTCtweets_Nov2020.txt'

    # The search_all method call the full-archive search endpoint to get Tweets based on the query, start and end times
    search_results = client.search_all(query=query, start_time=start_time, end_time=end_time, max_results=100)

    # Twarc returns all Tweets for the criteria set above, so we page through the results
    for page in search_results:
        # The Twitter API v2 returns the Tweet information and the user, media etc.  separately
        # so we use expansions.flatten to get all the information in a single JSON
        result = expansions.flatten(page)
        # We will open the file and append one JSON object per new line
        with open(file_name, 'a+') as filehandle:
            for tweet in result:
                #filehandle.write('%s\n' % json.dumps(tweet))
                filehandle.write('%s' % json.dumps(tweet["text"]))
                filehandle.write('%s\n' % json.dumps(tweet["created_at"]))

if __name__ == "__main__":
    main()

